contributors = [
    { name = "xHyroM", bio = "developer - random stuff", location = "Slovakia" },
    { name = "Devanshu2310", bio = "Software developer", location = "India" },
    { name = "Mukund32", bio = "developer - software", location = "India" },
    { name = "Shivaminc", bio = "Cybersecurity", location = "India" },
    { name = "NikoDyring", bio = "Fullstack Developer", location = "Denmark" }
]
